nhn-on7/marketgg-client

src/main/java/com/nhnacademy/marketgg/client/dto/LabelRegisterRequest.java, src/main/java/com/nhnacademy/marketgg/client/service/LabelService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelService.java, src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java, src/main/resources/templates/labels/create-form.html, src/main/resources/templates/labels/index.html, src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultLabelServiceTest.java, src/test/java/com/nhnacademy/marketgg/client/web/AdminLabelControllerTest.java
=> Feat: 라벨 등록 구현/테스트코드 작성 #1

src/main/java/com/nhnacademy/marketgg/client/adapter/ProductAdapter.java, src/main/java/com/nhnacademy/marketgg/client/adapter/impl/DefaultProductAdapter.java, src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductCreateRequest.java, src/main/java/com/nhnacademy/marketgg/client/service/DefaultProductService.java, src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java, src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java, src/main/resources/products/index.html
=> Feat: 상품 등록 기능 구현 #8

build.gradle, src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java, src/main/resources/application.yml
- Java Config 클래스 이름 수정
- gateway-origin 프로퍼티 추가
=> Refactor: Spring @Configuration annotation 수정 #37

build.gradle, src/main/java/com/nhnacademy/marketgg/client/web/AdminLabelController.java
개발 초기 단계라 앞으로 많이 반복될 것으로 예상되는 부분에서 리팩터링이 필요한 부분은 보일 때마다 PR 할게요.
궁금한 점 있다면 코멘트 바랍니다.
=> Refactor: AdminLabelController #39

src/main/java/com/nhnacademy/marketgg/client/adapter/ProductAdapter.java, src/main/java/com/nhnacademy/marketgg/client/adapter/impl/DefaultProductAdapter.java, src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java, src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
상품 삭제는 소프트 삭제로 구현하였습니다.
상태만 변경합니다.
=> Feat: 상품 삭제 기능 구현

src/main/resources/templates/categories/create-form.html, src/main/resources/templates/categories/index.html, src/main/resources/templates/categories/update-form.html
UI 구현 확인 부탁드립니다.
feature/category 로 병합 후 feature/category -> develop 병합하도록 합시다.
=> Feature/category UI

src/main/resources/static/js/toast.js, src/main/resources/templates/products/product-form.html
변경사항 
- Html: 디폴트 값 설정
- Javascript: Event action 변경 (mouseover -> click)
=> Fix: Toast API 관련 코드 수정

src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductCreateRequest.java, src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductModifyRequest.java, src/main/java/com/nhnacademy/marketgg/client/domain/dto/response/ProductResponse.java, src/main/java/com/nhnacademy/marketgg/client/repository/ProductRepository.java
=> Docs: 상품 레포지토리, DTO 자바독 작성 #59

src/main/java/com/nhnacademy/marketgg/client/annotation/NoAuth.java, src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java, src/main/java/com/nhnacademy/marketgg/client/config/InterceptorConfig.java, src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java, src/main/java/com/nhnacademy/marketgg/client/config/WebConfig.java, src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java, src/main/java/com/nhnacademy/marketgg/client/exception/LoginFailException.java, src/main/java/com/nhnacademy/marketgg/client/exception/LogoutException.java, src/main/java/com/nhnacademy/marketgg/client/interceptor/JwtRefreshInterceptor.java, src/main/java/com/nhnacademy/marketgg/client/jwt/JwtInfo.java, src/main/java/com/nhnacademy/marketgg/client/repository/AuthRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java, src/main/java/com/nhnacademy/marketgg/client/service/AuthService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultAuthService.java, src/main/java/com/nhnacademy/marketgg/client/web/AuthController.java, src/main/resources/application.yml
- #70 
- 인증이 필요하지 않은 메서드 호출 시 AOP 작동 되지 않도록 Annotation 추가
- `@NoAuth` Annotation 을 통해 불필요한 AOP 동작 방지
=> 불필요한 AOP 가 요청되지 않도록 Annotation 추가

src/main/java/com/nhnacademy/marketgg/client/dto/request/ProductCreateRequest.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/CommonResponse.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/ListResponse.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/ProductResponse.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/CategoryAdapter.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java, src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java, src/main/resources/templates/products/product-form.html, src/main/resources/templates/products/product-modify-form.html, src/main/resources/templates/products/retrieve-products.html, src/test/java/com/nhnacademy/marketgg/client/ClientApplicationTests.java
- 상품 등록시 카테고리, 라벨 추가하여 등록
- 공통 응답객체 + 페이지네이션 '일부' 구현. 
- 팀 코드 동기화를 위해 PR 요청
- 카테고리, 라벨 등록은 체크박스를 사용하여 구현
- 공통 응답객체는 미완성. 현재 전체 상품목록 조회 수정중
테스트코드 통과 확인 완료
=> 상품 관리 코드 동기화를 위한 PR

src/main/java/com/nhnacademy/marketgg/client/dto/request/EmailRequest.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupRequest.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToAuth.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToShopMember.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberUpdateToAuth.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/EmailExistResponse.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/EmailUseResponse.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/MemberSignupResponse.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/MemberUpdateToAuthResponse.java, src/main/java/com/nhnacademy/marketgg/client/exception/ServerException.java, src/main/java/com/nhnacademy/marketgg/client/repository/AuthRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java, src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java, src/main/java/com/nhnacademy/marketgg/client/web/MemberAjaxController.java, src/main/java/com/nhnacademy/marketgg/client/web/MemberController.java, src/main/resources/templates/member/signup.html, src/test/java/com/nhnacademy/marketgg/client/controller/MemberControllerTest.java
=> Feat: 회원가입, 회원정보 수정, 회원탈퇴

src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberSignupToShopMember.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/MemberWithdrawRequest.java, src/main/java/com/nhnacademy/marketgg/client/repository/AuthRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/AuthAdapter.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java
- #87 
- 회원탈퇴시 LocalDateTIme Formatting
- 코드 전반적인 Style 처리
- 오류 수정
=> Refactor: 회원탈퇴 로직 수정

src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java, src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java, src/main/java/com/nhnacademy/marketgg/client/config/RedisConfig.java, src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalExceptionAdvice.java
- AOP 를 이용하여 사용자 정보 주입
- 아래와 같이 사용 가능합니다.
```java
@GetMapping("/some")
public ModelAndView someMethod(Member member) {
...
}
```
=> Controller 클래스에 MemberInfo 전달

src/main/java/com/nhnacademy/marketgg/client/exception/ClientException.java, src/main/java/com/nhnacademy/marketgg/client/exception/NotFoundException.java, src/main/java/com/nhnacademy/marketgg/client/exception/ServerException.java, src/main/java/com/nhnacademy/marketgg/client/web/advice/AuthControllerAdvice.java, src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalControllerAdvice.java
- #99 
- 예외처리 템플릿을 만들었습니다.
- `GlobalControllerAdvice` 생성
- `AuthControllerAdvice` 생성
- 공통으로 처리될만한 Exception class 생성
- Validation 처리 Controller Advice 생성 필요
=> Feat: 예외 처리 템플릿 생성 #99

src/main/java/com/nhnacademy/marketgg/client/aspect/MemberAspect.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/ProductToCartRequest.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/CartProductResponse.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/ListResponse.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/common/ResponseUtils.java, src/main/java/com/nhnacademy/marketgg/client/exception/ClientException.java, src/main/java/com/nhnacademy/marketgg/client/exception/NotFoundException.java, src/main/java/com/nhnacademy/marketgg/client/exception/ServerException.java, src/main/java/com/nhnacademy/marketgg/client/exception/auth/UnAuthenticException.java, src/main/java/com/nhnacademy/marketgg/client/exception/auth/UnAuthorizationException.java, src/main/java/com/nhnacademy/marketgg/client/repository/CartRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/CartAdapter.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java, src/main/java/com/nhnacademy/marketgg/client/service/CartService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultCartService.java, src/main/java/com/nhnacademy/marketgg/client/web/CartController.java, src/main/java/com/nhnacademy/marketgg/client/web/advice/AuthControllerAdvice.java, src/main/java/com/nhnacademy/marketgg/client/web/advice/GlobalControllerAdvice.java
- #101 
- 클라이언트 서버 장바구니 요청에대한 기능 구현
- 장바구니 기능 구현
- 응답 처리 Util 클래스 구현 (/dto/response/common/ResponseUtils.java) 확인 바랍니다.
- view 페이지 추가 예정
=> 장바구니 기능 구현

src/main/java/com/nhnacademy/marketgg/client/repository/PostRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/PostAdapter.java, src/main/java/com/nhnacademy/marketgg/client/service/PostService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultPostService.java, src/main/java/com/nhnacademy/marketgg/client/web/AdminPostController.java, src/main/java/com/nhnacademy/marketgg/client/web/PostController.java, src/main/resources/templates/board/faqs/detail.html, src/main/resources/templates/board/faqs/index.html, src/main/resources/templates/board/notices/detail.html, src/main/resources/templates/board/notices/index.html, src/main/resources/templates/board/oto-inquiries/detail.html, src/main/resources/templates/board/oto-inquiries/index.html, src/main/resources/templates/board/oto-inquiries/update-form.html, src/test/java/com/nhnacademy/marketgg/client/service/PostServiceTest.java, src/test/java/com/nhnacademy/marketgg/client/web/AdminPostControllerTest.java, src/test/java/com/nhnacademy/marketgg/client/web/PostControllerTest.java
- closed #109 
- 게시판 내 매핑 오류 및 권한 에러 수정
- 1:1 문의 검색이 사용자도 가능했던 버그 수정
- 게시판 그만 만지고싶습니다.
=> 게시판 마지막 Fix

lombok.config, src/main/resources/templates/fragments/common/footer.html, src/main/resources/templates/fragments/common/gnb.html, src/main/resources/templates/fragments/common/header.html, src/main/resources/templates/fragments/products/create-form.html, src/main/resources/templates/fragments/products/table.html, src/main/resources/templates/index.html, src/main/resources/templates/pages/admin/index.html, src/main/resources/templates/pages/admin/products/form.html, src/main/resources/templates/pages/admin/products/index.html, src/main/resources/templates/pages/payments/index.html
- Closes #116 
```
resources/
|—— static/ (크게 커스터마이징한 것과(css, images, js) 갖다 쓰는 폴더(plugins)로 구분)
|      |—— css/ : Market GG 자체 제작한 커스터마이징 CSS 파일
|      |—— images/ : Market GG 에서 사용하는 이미지 파일
|      |—— js/ : Market GG 자체 제작한 커스터마이징 JavaScript 파일
|      |—— plugins/ : 사용한 라이브러리(각 플러그인 폴더 안에 css/, js/ 등으로 구분)
|—— templates/ (fragment < page < layout)
|—— fragments/ : <html>, <head>, <body> 가 없는 순수한 컴포넌트 모음
|—— layouts/ : 각 페이지(`pages에서 사용하며 뼈대가 되는 레이아웃
|—— pages/ : 실제 사용자가 보게 되는 페이지로, 컨트롤러는 모두 페이지에 매핑
```
=> UI 공통 컴포넌트 및 템플릿 작성

src/main/java/com/nhnacademy/marketgg/client/dto/request/SignupRequest.java, src/main/java/com/nhnacademy/marketgg/client/repository/MemberRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoAdapter.java, src/main/java/com/nhnacademy/marketgg/client/repository/auth/MemberInfoRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/impl/MemberAdapter.java, src/main/java/com/nhnacademy/marketgg/client/service/MemberService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultMemberService.java, src/main/java/com/nhnacademy/marketgg/client/web/MemberInfoController.java
=> 회원가입 로직 변경 

build.gradle, src/main/java/com/nhnacademy/marketgg/client/web/CsPostController.java, src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminCsPostController.java, src/main/resources/templates/pages/board/faqs/detail.html, src/main/resources/templates/pages/board/faqs/index.html, src/main/resources/templates/pages/board/notices/detail.html, src/main/resources/templates/pages/board/notices/index.html, src/main/resources/templates/pages/board/oto-inquiries/index.html
- #176 
- security 옵션으로 권한 설정 변경
- spring security 설정 변경
- optional
=> 고객센터 html 수정

src/main/java/com/nhnacademy/marketgg/client/web/IndexController.java, src/main/resources/static/plugins/marketgg/css/marketgg.index.css, src/main/resources/templates/index.html
- 상품 컨트롤러 URI 수정
- 인덱스 페이지에서 상품 조회 가능
=> Fix: 상품 전체조회 URI 수정

src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java, src/main/java/com/nhnacademy/marketgg/client/dto/response/ProductResponse.java, src/main/java/com/nhnacademy/marketgg/client/repository/product/ProductAdapter.java, src/main/java/com/nhnacademy/marketgg/client/repository/product/ProductRepository.java, src/main/java/com/nhnacademy/marketgg/client/repository/product/ReviewAdapter.java, src/main/java/com/nhnacademy/marketgg/client/repository/product/ReviewRepository.java, src/main/java/com/nhnacademy/marketgg/client/service/ProductService.java, src/main/java/com/nhnacademy/marketgg/client/service/ReviewService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java, src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultReviewService.java, src/main/java/com/nhnacademy/marketgg/client/web/admin/AdminProductController.java, src/main/java/com/nhnacademy/marketgg/client/web/product/ProductController.java, src/main/java/com/nhnacademy/marketgg/client/web/product/ReviewController.java, src/main/resources/application.yml, src/main/resources/static/css/products/reviews.css, src/main/resources/static/js/products/dib.js, src/main/resources/static/js/products/review-editor.js, src/main/resources/static/js/products/reviews.js, src/main/resources/static/plugins/tui/toast.js, src/main/resources/templates/fragments/common/gnb.html, src/main/resources/templates/fragments/products/details.html, src/main/resources/templates/fragments/products/reviews/reviews.html, src/main/resources/templates/layouts/title-main-link-script.html, src/main/resources/templates/pages/products/product-view.html, src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultReviewServiceTest.java, src/test/java/com/nhnacademy/marketgg/client/web/ReviewControllerTest.java
- 후기기능 구현
- 상품 상세조회 렌더링오류 수정
- 상품 상세조회페이지 렌더링 오류 수정
- 상품 후기기능 구현
- 메인페이지에서 카테고리 클릭시 해당 카테고리로 상품 조회기능 구현
=> 상품 후기 UI 구현 및 카테고리로 상품조회 구현

src/main/java/com/nhnacademy/marketgg/client/dto/order/OrderCreateRequest.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/CartOrderRequest.java, src/main/java/com/nhnacademy/marketgg/client/dto/request/ProductToCartRequest.java, src/main/java/com/nhnacademy/marketgg/client/web/cart/CartController.java, src/main/java/com/nhnacademy/marketgg/client/web/order/OrderPageController.java, src/main/resources/static/js/carts/cart.js, src/main/resources/static/js/products/product.js, src/main/resources/templates/fragments/common/header.html, src/main/resources/templates/fragments/products/details.html, src/main/resources/templates/pages/carts/index.html, src/test/java/com/nhnacademy/marketgg/client/service/impl/DefaultCartServiceTest.java, src/test/java/com/nhnacademy/marketgg/client/web/CartControllerTest.java
- #213 
- 장바구니 주문 연결
- 상품 번호만 전달 가능.
- 로직으로 주문 회원 조회 후 장바구니 번호 추가하여 선택된 상품 조회 해야할 듯
- 상품 장바구니 추가 시 JS 오류 있음 추후 해결 예정
=> Feat: 카트에서 주문으로 데이터 전송

src/main/java/com/nhnacademy/marketgg/client/config/WebSecurityConfig.java, src/main/java/com/nhnacademy/marketgg/client/web/IndexController.java, src/main/resources/static/css/label/marketgg.label.css, src/main/resources/static/css/mygg/marketgg.mygg.css, src/main/resources/static/js/common/backToTop.js, src/main/resources/static/js/common/viewport.js, src/main/resources/static/plugins/autocomplete/js/index.js, src/main/resources/static/plugins/clickymenus/css/clicky-menus.css, src/main/resources/static/plugins/marketgg/css/marketgg.common.css, src/main/resources/templates/fragments/common/footer.html, src/main/resources/templates/fragments/common/header.html, src/main/resources/templates/index.html, src/main/resources/templates/pages/admin/labels/index.html, src/main/resources/templates/pages/mygg/dibs/index.html, src/main/resources/templates/pages/mygg/index.html
=> 마이 페이지 UI 레이아웃 작성

src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
- 토큰 갱신 실패 시 세션의 토큰 삭제
- 로그인이 만료되었지만 토큰이 남아있어 로그인 해제가 되지않아 발생하던 장바구니 에러 해결
=> Refactor: 토큰 갱신 실패 시 Redis 에서 기존 토큰 삭제

src/main/resources/templates/pages/carts/index.html
=> Style: 장바구니 Input 태그 스타일 변경

src/main/java/com/nhnacademy/marketgg/client/web/auth/AuthController.java, src/main/resources/log4j2-prod.xml, src/main/resources/templates/index.html
- 로그아웃 오류 수정
- 로그아웃 후 메인 페이지 이동시 임시 방편으로 새로고침으로 해결
=> Hotfix: Logout 수정

src/main/java/com/nhnacademy/marketgg/client/aspect/JwtAspect.java
=> Hotfix: AOP 경로 변경
